image: node:14

pipelines:
  branches:
    sandbox:
      - step:
          name: Build
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploy
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: us-east-2
                S3_BUCKET: v2-app-prod
                ACL: "public-read"
                LOCAL_PATH: "dist"