const countries = [
  {
    country: "Argentina",
    dialing_code: "54",
    code: "ar",
    flag: "https://dyclassroom.com/image/flags/ar.png",
    currency: {
      sign: "$",
      short: "ARS",
      long: "Peso",
      description: "Argentine Peso",
    },
  },
  {
    country: "Australia",
    dialing_code: "61",
    code: "au",
    flag: "https://dyclassroom.com/image/flags/au.png",
    currency: {
      sign: "$",
      short: "AUD",
      long: "Dollar",
      description: "Australian Dollar",
    },
  },
  {
    country: "Brazil",
    dialing_code: "55",
    code: "br",
    flag: "https://dyclassroom.com/image/flags/br.png",
    currency: {
      sign: "R$",
      short: "BRL",
      long: "Real",
      description: "Brazilian Real",
    },
  },
  {
    country: "Cameroon",
    dialing_code: "237",
    code: "cm",
    flag: "https://dyclassroom.com/image/flags/cm.png",
    currency: {
      sign: "XAF",
      short: "FCFA",
      long: "CFA Franc",
      description: "Central African CFA Franc",
    },
  },
  {
    country: "Canada",
    dialing_code: "1",
    code: "ca",
    flag: "https://dyclassroom.com/image/flags/ca.png",
    currency: {
      sign: "$",
      short: "CAD",
      long: "Dollar",
      description: "Canadian Dollar",
    },
  },
  {
    country: "Denmark",
    dialing_code: "45",
    code: "dk",
    flag: "https://dyclassroom.com/image/flags/dk.png",
    currency: {
      sign: "kr",
      short: "DKK",
      long: "Krone",
      description: "Danish Krone",
    },
  },
  {
    country: "Ecuador",
    dialing_code: "593",
    code: "ec",
    flag: "https://dyclassroom.com/image/flags/ec.png",
    currency: {
      sign: "$",
      short: "USD",
      long: "Dollar",
      description: "United States Dollar",
    },
  },
  {
    country: "Egypt",
    dialing_code: "20",
    code: "eg",
    flag: "https://dyclassroom.com/image/flags/eg.png",
    currency: {
      sign: "E£",
      short: "EGP",
      long: "Pound",
      description: "Egyptian Pound",
    },
  },
  {
    country: "France",
    dialing_code: "33",
    code: "fr",
    flag: "https://dyclassroom.com/image/flags/fr.png",
    currency: {
      sign: "€",
      short: "EUR",
      long: "Euro",
      description: "Euro",
    },
  },
  {
    country: "Gabon",
    dialing_code: "241",
    code: "ga",
    flag: "https://dyclassroom.com/image/flags/ga.png",
    currency: {
      sign: "FCF",
      short: "XAF",
      long: "CFA franc",
      description: "Central African CFA franc",
    },
  },
  {
    country: "Germany",
    dialing_code: "49",
    code: "de",
    flag: "https://dyclassroom.com/image/flags/de.png",
    currency: {
      sign: "€",
      short: "EUR",
      long: "Euro",
      description: "Euro",
    },
  },
  {
    country: "Ghana",
    dialing_code: "233",
    code: "gh",
    flag: "https://dyclassroom.com/image/flags/gh.png",
    currency: {
      sign: "GH₵",
      short: "GHS",
      long: "Cedi",
      description: "Ghanaian Cedi",
    },
  },
  {
    country: "Ivory Coast",
    dialing_code: "225",
    code: "ci",
    flag: "https://dyclassroom.com/image/flags/ci.png",
    currency: {
      sign: "CFA",
      short: "XOF",
      long: "CFA franc",
      description: "West African CFA franc",
    },
  },
  {
    country: "Jamaica",
    dialing_code: "1-876",
    code: "jm",
    flag: "https://dyclassroom.com/image/flags/jm.png",
    currency: {
      sign: "J$",
      short: "JMD",
      long: "Dollar",
      description: "Jamaican Dollar",
    },
  },
  {
    country: "Kenya",
    dialing_code: "254",
    code: "ke",
    flag: "https://dyclassroom.com/image/flags/ke.png",
    currency: {
      sign: "KSh",
      short: "KES",
      long: "Shilling",
      description: "Kenyan Shilling",
    },
  },
  {
    country: "Mali",
    dialing_code: "223",
    code: "ml",
    flag: "https://dyclassroom.com/image/flags/ml.png",
    currency: {
      sign: "CFA",
      short: "XOF",
      long: "CFA franc",
      description: "West African CFA franc",
    },
  },
  {
    country: "Mexico",
    dialing_code: "52",
    code: "mx",
    flag: "https://dyclassroom.com/image/flags/mx.png",
    currency: {
      sign: "$",
      short: "MXN",
      long: "Peso",
      description: "Mexican Peso",
    },
  },
  {
    country: "Netherlands",
    dialing_code: "31",
    code: "nl",
    flag: "https://dyclassroom.com/image/flags/nl.png",
    currency: {
      sign: "€",
      short: "EUR",
      long: "Euro",
      description: "Euro",
    },
  },
  {
    country: "New Zealand",
    dialing_code: "64",
    code: "nz",
    flag: "https://dyclassroom.com/image/flags/nz.png",
    currency: {
      sign: "$",
      short: "NZD",
      long: "Dollar",
      description: "New Zealand Dollar",
    },
  },
  {
    country: "Nigeria",
    dialing_code: "234",
    code: "ng",
    flag: "https://dyclassroom.com/image/flags/ng.png",
    currency: {
      sign: "₦",
      short: "NGN",
      long: "Naira",
      description: "Nigerian Naira",
    },
  },
  {
    country: "North Korea",
    dialing_code: "850",
    code: "kp",
    flag: "https://dyclassroom.com/image/flags/kp.png",
    currency: {
      sign: "₩",
      short: "KPW",
      long: "Won",
      description: "North Korean Won",
    },
  },
  {
    country: "Norway",
    dialing_code: "47",
    code: "no",
    flag: "https://dyclassroom.com/image/flags/no.png",
    currency: {
      sign: "kr",
      short: "NOK",
      long: "Krone",
      description: "Norwegian Krone",
    },
  },
  {
    country: "Oman",
    dialing_code: "968",
    code: "om",
    flag: "https://dyclassroom.com/image/flags/om.png",
    currency: {
      sign: "ر.ع.",
      short: "OMR",
      long: "Rial",
      description: "Omani Rial",
    },
  },
  {
    country: "Pakistan",
    dialing_code: "92",
    code: "pk",
    flag: "https://dyclassroom.com/image/flags/pk.png",
    currency: {
      sign: "₨",
      short: "PKR",
      long: "Rupee",
      description: "Pakistani Rupee",
    },
  },
  {
    country: "Paraguay",
    dialing_code: "595",
    code: "py",
    flag: "https://dyclassroom.com/image/flags/py.png",
    currency: {
      sign: "₲",
      short: "PYG",
      long: "Guarani",
      description: "Paraguayan Guarani",
    },
  },
  {
    country: "Peru",
    dialing_code: "51",
    code: "pe",
    flag: "https://dyclassroom.com/image/flags/pe.png",
    currency: {
      sign: "S/.",
      short: "PEN",
      long: "Sol",
      description: "Peruvian Sol",
    },
  },
  {
    country: "Philippines",
    dialing_code: "63",
    code: "ph",
    flag: "https://dyclassroom.com/image/flags/ph.png",
    currency: {
      sign: "₱",
      short: "PHP",
      long: "Peso",
      description: "Philippine Peso",
    },
  },
  {
    country: "Poland",
    dialing_code: "48",
    code: "pl",
    flag: "https://dyclassroom.com/image/flags/pl.png",
    currency: {
      sign: "zł",
      short: "PLN",
      long: "Złoty",
      description: "Polish Złoty",
    },
  },
  {
    country: "Portugal",
    dialing_code: "351",
    code: "pt",
    flag: "https://dyclassroom.com/image/flags/pt.png",
    currency: {
      sign: "€",
      short: "EUR",
      long: "Euro",
      description: "Euro",
    },
  },
  {
    country: "Qatar",
    dialing_code: "974",
    code: "qa",
    flag: "https://dyclassroom.com/image/flags/qa.png",
    currency: {
      sign: "ر.ق",
      short: "QAR",
      long: "Riyal",
      description: "Qatari Riyal",
    },
  },
  {
    country: "Republic of the Congo",
    dialing_code: "242",
    code: "cg",
    flag: "https://dyclassroom.com/image/flags/cg.png",
    currency: {
      sign: "FC",
      short: "XAF",
      long: "CFA franc",
      description: "Central African CFA franc",
    },
  },
  {
    country: "Romania",
    dialing_code: "40",
    code: "ro",
    flag: "https://dyclassroom.com/image/flags/ro.png",
    currency: {
      sign: "lei",
      short: "RON",
      long: "Leu",
      description: "Romanian Leu",
    },
  },
  {
    country: "Russia",
    dialing_code: "7",
    code: "ru",
    flag: "https://dyclassroom.com/image/flags/ru.png",
    currency: {
      sign: "₽",
      short: "RUB",
      long: "Ruble",
      description: "Russian Ruble",
    },
  },
  {
    country: "Rwanda",
    dialing_code: "250",
    code: "rw",
    flag: "https://dyclassroom.com/image/flags/rw.png",
    currency: {
      sign: "RWF",
      short: "RWF",
      long: "franc",
      description: "Rwandan franc",
    },
  },
  {
    country: "Senegal",
    dialing_code: "221",
    code: "sn",
    flag: "https://dyclassroom.com/image/flags/sn.png",
    currency: {
      sign: "CFA",
      short: "XOF",
      long: "CFA franc",
      description: "West African CFA franc",
    },
  },
  {
    country: "South Africa",
    dialing_code: "27",
    code: "za",
    flag: "https://dyclassroom.com/image/flags/za.png",
    currency: {
      sign: "R",
      short: "ZAR",
      long: "Rand",
      description: "South African rand",
    },
  },
  {
    country: "Spain",
    dialing_code: "34",
    code: "es",
    flag: "https://dyclassroom.com/image/flags/es.png",
    currency: {
      sign: "€",
      short: "EUR",
      long: "Euro",
      description: "Euro",
    },
  },
  {
    country: "Tanzania",
    dialing_code: "255",
    code: "tz",
    flag: "https://dyclassroom.com/image/flags/tz.png",
    currency: {
      sign: "TZS",
      short: "TZS",
      long: "Shilling",
      description: "Tanzanian shilling",
    },
  },
  {
    country: "Togo",
    dialing_code: "228",
    code: "tg",
    flag: "https://dyclassroom.com/image/flags/tg.png",
    currency: {
      sign: "CFA",
      short: "XOF",
      long: "CFA franc",
      description: "West African CFA franc",
    },
  },
  {
    country: "Tunisia",
    dialing_code: "216",
    code: "tn",
    flag: "https://dyclassroom.com/image/flags/tn.png",
    currency: {
      sign: "DT",
      short: "TND",
      long: "Dinar",
      description: "Tunisian dinar",
    },
  },
  {
    country: "Turkey",
    dialing_code: "90",
    code: "tr",
    flag: "https://dyclassroom.com/image/flags/tr.png",
    currency: {
      sign: "₺",
      short: "TRY",
      long: "Lira",
      description: "Turkish Lira",
    },
  },
  {
    country: "Ukraine",
    dialing_code: "380",
    code: "ua",
    flag: "https://dyclassroom.com/image/flags/ua.png",
    currency: {
      sign: "₴",
      short: "UAH",
      long: "Hryvnia",
      description: "Ukrainian Hryvnia",
    },
  },
  {
    country: "United Arab Emirates",
    dialing_code: "971",
    code: "ae",
    flag: "https://dyclassroom.com/image/flags/ae.png",
    currency: {
      sign: "د.إ",
      short: "AED",
      long: "Dirham",
      description: "United Arab Emirates Dirham",
    },
  },
  {
    country: "United Kingdom",
    dialing_code: "44",
    code: "gb",
    flag: "https://dyclassroom.com/image/flags/gb.png",
    currency: {
      sign: "£",
      short: "GBP",
      long: "Pound Sterling",
      description: "British Pound Sterling",
    },
  },
  {
    country: "United States",
    dialing_code: "1",
    code: "us",
    flag: "https://dyclassroom.com/image/flags/us.png",
    currency: {
      sign: "$",
      short: "USD",
      long: "Dollar",
      description: "United States Dollar",
    },
  },
  {
    country: "Zambia",
    dialing_code: "260",
    code: "zm",
    flag: "https://dyclassroom.com/image/flags/zm.png",
    currency: {
      sign: "ZK",
      short: "ZMW",
      long: "Kwacha",
      description: "Zambian Kwacha",
    },
  },
  {
    country: "Zimbabwe",
    dialing_code: "263",
    code: "zw",
    flag: "https://dyclassroom.com/image/flags/zw.png",
    currency: {
      sign: "$",
      short: "ZWL",
      long: "Dollar",
      description: "Zimbabwean Dollar",
    },
  },
];

export default countries;
