const sidebarRoutes = [
  {
    id: 1,
    title: "Overview",
    icon: "DashboardIcon",
    link: "/dashboard",
    slug: "dashboard",
  },
  {
    id: 2,
    title: "Escrow Transactions",
    icon: "TransactionIcon",
    link: "/escrow/transactions",
    slug: "transactions",
  },
  {
    id: 3,
    title: "MoR Metrics",
    icon: "PaymentIcon",
    link: "/merchant/mor-transaction",
    slug: "mor-transaction",
  },
  {
    id: 4,
    title: "Payments",
    icon: "FundIcon",
    link: "/payments",
    slug: "payments",
  },
  {
    id: 5,
    title: "Foreign Exchange",
    icon: "ExchangeIcon",
    link: "/exchange",
    slug: "exchange",
  },
  // {
  //   id: 6,
  //   title: "Tax Records",
  //   icon: "TaxIcon",
  //   link: "/merchant/tax-record",
  //   slug: "tax-record",
  // },
  // {
  //   id: 7,
  //   title: "Reports",
  //   icon: "ChartIcon",
  //   link: "/payments",
  //   slug: "payments",
  //   tour_id: [],
  // },
  // {
  //   id: 8,
  //   title: "Customers",
  //   icon: "CustomerIcon",
  //   link: "/payments",
  //   slug: "payments",
  //   tour_id: [],
  // },
  {
    id: 9,
    title: "Developers",
    icon: "DeveloperIcon",
    link: "/merchant/developer?type=api_key",
    slug: "developer",
  },
  {
    id: 10,
    title: "Settings",
    icon: "SettingsIcon",
    link: "/settings/profile",
    slug: "settings",
  },
];

export { sidebarRoutes };
